void loop() {
  const int relaisIN1 = 22;
  const int relaisIN2 = 23;
  const int relaisIN3 = 24;
  const int relaisIN4 = 25;
  const int relaisIN5 = 26;
  const int relaisIN6 = 27;
  const int relaisIN7 = 28;
  const int relaisIN8 = 29;
  const int relaisIN9 = 30;
  const int relaisIN10 = 31;
  const int relaisIN11 = 32;
  const int relaisIN12 = 33;
  const int relaisIN13 = 34;
  const int relaisIN14 = 35;
  const int relaisIN15 = 36;
  const int relaisIN16 = 37;
  const int relaisIN17 = 38;
  const int relaisIN18 = 39;
  const int relaisIN19 = 40;
  const int relaisIN20 = 41;
  const int relaisIN21 = 42;
  const int relaisIN22 = 43;
  const int relaisIN23 = 44;
  const int relaisIN24 = 45;
  const int relaisIN25 = 46;
  const int relaisIN26 = 47;
  const int relaisIN27 = 48;
  pinMode(relaisIN1, OUTPUT);
  pinMode(relaisIN2, OUTPUT);
  pinMode(relaisIN3, OUTPUT);
  pinMode(relaisIN4, OUTPUT);
  pinMode(relaisIN5, OUTPUT);
  pinMode(relaisIN6, OUTPUT);
  pinMode(relaisIN7, OUTPUT);
  pinMode(relaisIN8, OUTPUT);
  pinMode(relaisIN9, OUTPUT);
  pinMode(relaisIN10, OUTPUT);
  pinMode(relaisIN11, OUTPUT);
  pinMode(relaisIN12, OUTPUT);
  pinMode(relaisIN13, OUTPUT);
  pinMode(relaisIN14, OUTPUT);
  pinMode(relaisIN15, OUTPUT);
  pinMode(relaisIN16, OUTPUT);
  pinMode(relaisIN17, OUTPUT);
  pinMode(relaisIN18, OUTPUT);
  pinMode(relaisIN19, OUTPUT);
  pinMode(relaisIN20, OUTPUT);
  pinMode(relaisIN21, OUTPUT);
  pinMode(relaisIN22, OUTPUT);
  pinMode(relaisIN23, OUTPUT);
  pinMode(relaisIN24, OUTPUT);
  pinMode(relaisIN25, OUTPUT);
  pinMode(relaisIN26, OUTPUT);
  pinMode(relaisIN27, OUTPUT);

  digitalWrite(relaisIN1, HIGH); 
  delay(500);
  digitalWrite(relaisIN2, HIGH); 
  delay(500);
  digitalWrite(relaisIN3, HIGH); 
  delay(500);
  digitalWrite(relaisIN4, HIGH); 
  delay(500);
  digitalWrite(relaisIN5, HIGH); 
  delay(500);
  digitalWrite(relaisIN6, HIGH); 
  delay(500);
  digitalWrite(relaisIN7, HIGH); 
  delay(500);
  digitalWrite(relaisIN8, HIGH); 
  delay(500);
  digitalWrite(relaisIN9, HIGH); 
  delay(500);
  digitalWrite(relaisIN10, HIGH); 
  delay(500);
  digitalWrite(relaisIN11, HIGH); 
  delay(500);
  digitalWrite(relaisIN12, HIGH); 
  delay(500);
  digitalWrite(relaisIN13, HIGH); 
  delay(500);
  digitalWrite(relaisIN14, HIGH); 
  delay(500);
  digitalWrite(relaisIN15, HIGH); 
  delay(500);
  digitalWrite(relaisIN16, HIGH); 
  delay(500);
  digitalWrite(relaisIN17, HIGH); 
  delay(500);
  digitalWrite(relaisIN18, HIGH); 
  delay(500);
  digitalWrite(relaisIN19, HIGH); 
  delay(500);
  digitalWrite(relaisIN20, HIGH); 
  delay(500);
  digitalWrite(relaisIN21, HIGH); 
  delay(500);
  digitalWrite(relaisIN22, HIGH); 
  delay(500);
  digitalWrite(relaisIN23, HIGH); 
  delay(500);
  digitalWrite(relaisIN24, HIGH); 
  delay(500);
  digitalWrite(relaisIN25, HIGH); 
  delay(500);
  digitalWrite(relaisIN26, HIGH); 
  delay(500);
  digitalWrite(relaisIN27, HIGH); 
  delay(500);
  
  digitalWrite(relaisIN1, LOW); 
  delay(500);
  digitalWrite(relaisIN2, LOW); 
  delay(500);
  digitalWrite(relaisIN3, LOW); 
  delay(500);
  digitalWrite(relaisIN4, LOW); 
  delay(500);
  digitalWrite(relaisIN5, LOW); 
  delay(500);
  digitalWrite(relaisIN6, LOW); 
  delay(500);
  digitalWrite(relaisIN7, LOW); 
  delay(500);
  digitalWrite(relaisIN8, LOW); 
  delay(500);
  digitalWrite(relaisIN9, LOW); 
  delay(500);
  digitalWrite(relaisIN10, LOW); 
  delay(500);
  digitalWrite(relaisIN11, LOW); 
  delay(500);
  digitalWrite(relaisIN12, LOW); 
  delay(500);
  digitalWrite(relaisIN13, LOW); 
  delay(500);
  digitalWrite(relaisIN14, LOW); 
  delay(500);
  digitalWrite(relaisIN15, LOW); 
  delay(500);
  digitalWrite(relaisIN16, LOW); 
  delay(500);
  digitalWrite(relaisIN17, LOW); 
  delay(500);
  digitalWrite(relaisIN18, LOW); 
  delay(500);
  digitalWrite(relaisIN19, LOW); 
  delay(500);
  digitalWrite(relaisIN20, LOW); 
  delay(500);
  digitalWrite(relaisIN21, LOW); 
  delay(500);
  digitalWrite(relaisIN22, LOW); 
  delay(500);
  digitalWrite(relaisIN23, LOW); 
  delay(500);
  digitalWrite(relaisIN24, LOW); 
  delay(500);
  digitalWrite(relaisIN25, LOW); 
  delay(500);
  digitalWrite(relaisIN26, LOW); 
  delay(500);
  digitalWrite(relaisIN27, LOW); 
  delay(500);

}

void setup() {

}
